project:
  type: website
  output-dir: docs

  preview: 
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true

website:
  title: "Helpman Institute"
  #favicon: "/files/icon.png"
  site-url: "https://www.helpmaninstitute.org"
  #repo-url: "https://github.com/helpmaninstitute/website"
  
  navbar:
    pinned: true

    left:
      - text: "Research"
        href: "index.qmd"
        
    right:
      - icon: envelope
        aria-label: email
        href: "mailto:info@helpmaninstitute.org"
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/company/helpmaninstitute

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    embed-resources: false

editor: visual

